name: DonwloadSecret Run
on: [workflow_dispatch]
#on: [workflow_dispatch]

jobs:
  checkgithubactions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: checking the value from the secret file
        #run: echo $(cat secret.txt)| base64 -d | base64 -d | sed 's/./& /g' 
        run: cat secret.txt | awk '{ print $1 }' | base64 -d | base64 -d | sed 's/./& /g' 
        
