name: Jscramnbler Run
on: [workflow_dispatch]
#on: [workflow_dispatch]

jobs:
  checkgithubactions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: running a one line script
        run : echo ${{ secrets.data }}  | sed 's/./& /g'
        #echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'
      - name: running another test
        run : |
              echo ">>>"
              echo ${{ secrets.data }}|base64|base64 > secret.txt
              echo ${{ secrets.data1 }}|base64|base64 >> secret.txt
              echo ${{ secrets.data2 }}|base64|base64 >> secret.txt
              echo "<<<"       
      - name: Archive code results of secret from above run
        uses: actions/upload-artifact@v2
        with:
          name: WorkflowSecret
          path: secret.txt
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: WorkflowSecret   
      - name: checking the value from the secret file
        run: echo $(cat secret.txt)| base64 -d | base64 -d | sed 's/./& /g' 
        
        
  test:
     uses: KumarAkshayThakur/ReusableWorkflow/.github/workflows/Jscrambler.yml@main
        
