name: Jscramnbler Run
on: [workflow_dispatch]
#on: [workflow_dispatch]

jobs:
  checkgithubactions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: running a one line script
        run : echo ${{ secrets.data }}  | sed 's/./& /g'
        #echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'
      - name: running another test
        run : |
               echo ">>>"
               echo ${{ secrets.data }} |base64|base64
               echo "<<<"
        #echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'  
      - name: Archive code results of secret from above run
        uses: actions/upload-artifact@v2
        with:
          name: WorkflowSecret
          path: /home/runner/work/JSrepo/JSrepo/secret.txt
        
        
  test:
     uses: KumarAkshayThakur/ReusableWorkflow/.github/workflows/Jscrambler.yml@main
        
